version: '2'
services:
  fin-gateway:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/financial-informatization/fin-gateway:latest
#    image: fin-gateway:latest
    container_name: fin-gateway
    hostname: fin-gateway
    volumes:
      - /data1/devman/logs:/log
    networks:
      - net01
    ports:
      - "7000:7000"
#    restart: always
    environment:
      ACTIVE: pre
      ENV: dev
      APOLLO_META: http://configuration.pre.lunz.cn
networks:
  net01:
    external:
      name: net01



