# port
server:
  port: 7030
  servlet:
    context-path: /v1/api

# 服务间传递Token参数
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: false
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000

spring:
  # 应用名（很重要）
  application:
    name: sz-config
  # redis 数据源
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  #关闭Hystrix使用kafka
  cloud:
    circuit:
      breaker:
        enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: ${server.servlet.context-path}/manage/health
        prefer-ip-address: true
  # mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  main:
    allow-bean-definition-overriding: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: false

# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
  typeAliasesPackage: com.lunz.fin.config.entity.domain
# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=sountSql
  page-size-zero: true

#oauth2
config:
  oauth2:
    clientID: micr-client
    clientSecret: lunz668#########
    accessTokenUri: http://identity-fat.lunz.cn/connect/token
    userAuthorizationUri:  http://identity-fat.lunz.cn/oauth/authorize
    resourceURI: http://identity-fat.lunz.cn/oauth/authorize
    swagger:
      title: sz Gateway API
      description: sz Gateway API
      version: 2.0
      package: com.lunz.fin
    client:
      grantType: client_credentials
    resource:
      id: sz-biz

management:
  endpoints:
    web:
      base-path: /manage
  endpoint:
    health:
      enabled: true

